import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'
import GlobalStyle from './globals'
import * as S from './styles'
import Menu from '@/components/Menu'

const LeagueSpartan = League_Spartan({
  subsets: ['latin-ext'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <GlobalStyle />
      <body className={LeagueSpartan.className}>
        <S.Container>
          <Menu />
          <S.Content>{children}</S.Content>
        </S.Container>
      </body>
    </html>
  )
}
