import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'
import GlobalStyle from './globals'
import * as S from './styles'
import Menu from '@/components/Menu'
import StyledComponentsRegistry from '@/lib/registry'

const LeagueSpartan = League_Spartan({
  subsets: ['latin-ext'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={LeagueSpartan.className}>
        <StyledComponentsRegistry>
          <GlobalStyle />
          <S.Container>
            <Menu />
            <S.Content>{children}</S.Content>
          </S.Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
